# Generated by Django 2.2.8 on 2019-12-23 10:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_quake', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0, tzinfo=utc))),
                ('url', models.URLField(unique=True)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('depth', models.DecimalField(decimal_places=1, max_digits=4)),
                ('magnitude', models.DecimalField(decimal_places=1, max_digits=3)),
                ('location', models.CharField(default='', max_length=2048)),
            ],
            options={
                'ordering': ['-time_of_quake'],
            },
        ),
        migrations.AddIndex(
            model_name='bulletinupdate',
            index=models.Index(fields=['time_of_quake'], name='bulletin_bu_time_of_9e0643_idx'),
        ),
        migrations.AddIndex(
            model_name='bulletinupdate',
            index=models.Index(fields=['url'], name='bulletin_bu_url_4b9def_idx'),
        ),
    ]
