# Generated by Django 2.2.8 on 2019-12-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BulletinUpdate',
            new_name='Bulletin',
        ),
        migrations.RemoveIndex(
            model_name='bulletin',
            name='bulletin_bu_time_of_9e0643_idx',
        ),
        migrations.RemoveIndex(
            model_name='bulletin',
            name='bulletin_bu_url_4b9def_idx',
        ),
        migrations.AddIndex(
            model_name='bulletin',
            index=models.Index(fields=['time_of_quake'], name='bulletin_bu_time_of_bd79fe_idx'),
        ),
        migrations.AddIndex(
            model_name='bulletin',
            index=models.Index(fields=['url'], name='bulletin_bu_url_820e24_idx'),
        ),
    ]
