# Generated by Django 3.0.2 on 2020-02-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0002_auto_20191223_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='time_of_quake',
            field=models.DateTimeField(null=True),
        ),
    ]
