# Generated by Django 3.0.2 on 2020-02-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0003_auto_20200207_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='scraped_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
